### ISSUE TITLE
Issue getting rid of hungry files

### ISSUE THREAD

**Issue by iqueiroz** [TiagoDanin/Thanos-NodeJS#1]
Came across this issue here while trying to fix a hungry universe:

```
$ node ./node_modules/thanos-nodejs/index.js  --universe ./
module.js:550
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Temp\logs\node_modules\thanos-nodejs\index.js:5:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Can you help me?
Thanks

**Comment by TiagoDanin** [comment]
[Install](https://github.com/TiagoDanin/Thanos-NodeJS#installation) the dependency, via Yarn or NPM.
